// Generated by scripts/generate-svg-assets.py. Do not edit by hand.
import type { FC } from 'react';
import type { SvgProps } from 'react-native-svg';

import type { SkinTone } from '@/domain/types';

import ChildAvatar from './child.svg';
import ChildMediumLightAvatar from './child-medium-light.svg';
import ChildMediumAvatar from './child-medium.svg';
import ChildMediumDarkAvatar from './child-medium-dark.svg';
import ChildDarkAvatar from './child-dark.svg';
import GirlAvatar from './girl.svg';
import GirlMediumLightAvatar from './girl-medium-light.svg';
import GirlMediumAvatar from './girl-medium.svg';
import GirlMediumDarkAvatar from './girl-medium-dark.svg';
import GirlDarkAvatar from './girl-dark.svg';
import BabyAvatar from './baby.svg';
import BabyMediumLightAvatar from './baby-medium-light.svg';
import BabyMediumAvatar from './baby-medium.svg';
import BabyMediumDarkAvatar from './baby-medium-dark.svg';
import BabyDarkAvatar from './baby-dark.svg';
import AdultAvatar from './adult.svg';
import AdultMediumLightAvatar from './adult-medium-light.svg';
import AdultMediumAvatar from './adult-medium.svg';
import AdultMediumDarkAvatar from './adult-medium-dark.svg';
import AdultDarkAvatar from './adult-dark.svg';
import ManAvatar from './man.svg';
import ManMediumLightAvatar from './man-medium-light.svg';
import ManMediumAvatar from './man-medium.svg';
import ManMediumDarkAvatar from './man-medium-dark.svg';
import ManDarkAvatar from './man-dark.svg';
import ElderlyAvatar from './elderly.svg';
import ElderlyMediumLightAvatar from './elderly-medium-light.svg';
import ElderlyMediumAvatar from './elderly-medium.svg';
import ElderlyMediumDarkAvatar from './elderly-medium-dark.svg';
import ElderlyDarkAvatar from './elderly-dark.svg';
import ElderlyManAvatar from './elderly-man.svg';
import ElderlyManMediumLightAvatar from './elderly-man-medium-light.svg';
import ElderlyManMediumAvatar from './elderly-man-medium.svg';
import ElderlyManMediumDarkAvatar from './elderly-man-medium-dark.svg';
import ElderlyManDarkAvatar from './elderly-man-dark.svg';
import PetAvatar from './pet.svg';
import LabradorAvatar from './labrador.svg';
import HuskyAvatar from './husky.svg';
import BoxerAvatar from './boxer.svg';
import CarameloAvatar from './caramelo.svg';
import CatAvatar from './cat.svg';
import BlackCatAvatar from './black-cat.svg';
import WhiteCatAvatar from './white-cat.svg';
import TricolorCatAvatar from './tricolor-cat.svg';
import RabbitAvatar from './rabbit.svg';
import BirdAvatar from './bird.svg';
import FishAvatar from './fish.svg';
import HamsterAvatar from './hamster.svg';
import TurtleAvatar from './turtle.svg';
import LizardAvatar from './lizard.svg';
import SnakeAvatar from './snake.svg';
import RobotAvatar from './robot.svg';
import PlantAvatar from './plant.svg';
import PottedPlantAvatar from './potted-plant.svg';
import CactusAvatar from './cactus.svg';
import SunflowerAvatar from './sunflower.svg';
import SucculentAvatar from './succulent.svg';
import OrchidAvatar from './orchid.svg';
import FernAvatar from './fern.svg';

/** People avatars have one illustration per skin tone; the others have one. */
export const AVATAR_ART: Record<string, FC<SvgProps> | Record<SkinTone, FC<SvgProps>>> = {
  'svg:child': {
    'light': ChildAvatar,
    'medium-light': ChildMediumLightAvatar,
    'medium': ChildMediumAvatar,
    'medium-dark': ChildMediumDarkAvatar,
    'dark': ChildDarkAvatar,
  },
  'svg:girl': {
    'light': GirlAvatar,
    'medium-light': GirlMediumLightAvatar,
    'medium': GirlMediumAvatar,
    'medium-dark': GirlMediumDarkAvatar,
    'dark': GirlDarkAvatar,
  },
  'svg:baby': {
    'light': BabyAvatar,
    'medium-light': BabyMediumLightAvatar,
    'medium': BabyMediumAvatar,
    'medium-dark': BabyMediumDarkAvatar,
    'dark': BabyDarkAvatar,
  },
  'svg:adult': {
    'light': AdultAvatar,
    'medium-light': AdultMediumLightAvatar,
    'medium': AdultMediumAvatar,
    'medium-dark': AdultMediumDarkAvatar,
    'dark': AdultDarkAvatar,
  },
  'svg:man': {
    'light': ManAvatar,
    'medium-light': ManMediumLightAvatar,
    'medium': ManMediumAvatar,
    'medium-dark': ManMediumDarkAvatar,
    'dark': ManDarkAvatar,
  },
  'svg:elderly': {
    'light': ElderlyAvatar,
    'medium-light': ElderlyMediumLightAvatar,
    'medium': ElderlyMediumAvatar,
    'medium-dark': ElderlyMediumDarkAvatar,
    'dark': ElderlyDarkAvatar,
  },
  'svg:elderly-man': {
    'light': ElderlyManAvatar,
    'medium-light': ElderlyManMediumLightAvatar,
    'medium': ElderlyManMediumAvatar,
    'medium-dark': ElderlyManMediumDarkAvatar,
    'dark': ElderlyManDarkAvatar,
  },
  'svg:pet': PetAvatar,
  'svg:labrador': LabradorAvatar,
  'svg:husky': HuskyAvatar,
  'svg:boxer': BoxerAvatar,
  'svg:caramelo': CarameloAvatar,
  'svg:cat': CatAvatar,
  'svg:black-cat': BlackCatAvatar,
  'svg:white-cat': WhiteCatAvatar,
  'svg:tricolor-cat': TricolorCatAvatar,
  'svg:rabbit': RabbitAvatar,
  'svg:bird': BirdAvatar,
  'svg:fish': FishAvatar,
  'svg:hamster': HamsterAvatar,
  'svg:turtle': TurtleAvatar,
  'svg:lizard': LizardAvatar,
  'svg:snake': SnakeAvatar,
  'svg:robot': RobotAvatar,
  'svg:plant': PlantAvatar,
  'svg:potted-plant': PottedPlantAvatar,
  'svg:cactus': CactusAvatar,
  'svg:sunflower': SunflowerAvatar,
  'svg:succulent': SucculentAvatar,
  'svg:orchid': OrchidAvatar,
  'svg:fern': FernAvatar,
};
